services:
  - type: web
    name: emotion-bot
    runtime: python
    pythonVersion: "3.11.8" #"3.12.7"
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.8" #"3.12.7"